name: Artifacts Deep

on:
  push:

jobs:
  upload-artifact:
    name: Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Create a local file
        run: echo "Hi, I am storing this data in this file, so that I can use this in the subsequent jobs within this workflow run. I will upload this file to Github storage and download from there when needed in this workflow run." > file.txt
      
      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: file
          path: file.txt
          retention-days: 10

  download-artifact:
    name: Download Artifact
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: file

      - name: Printing the file content
        run: cat file.txt
