name: GitHub Environments

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-22.04
    environment:
      name: production
      url: https://github.com
    steps:
      - name: Print secret from environment
        run: |
          echo "APP_SECRET: ${{ secrets.APP_SECRET }}"
