name: List all default GitHub Vars

on:
  workflow_dispatch:

jobs:
  ubuntu-environment-variables:
    runs-on: ubuntu-20.04
    steps:
      - run: env

  windows-environment-variables:
    runs-on: windows-latest
    steps:
      - run: env

  macos-environment-variables:
    runs-on: macos-latest
    steps:
      - run: env
