name: 'custom GITHUB_env variables'

on: workflow_dispatch

jobs:
  custom_GITHUB_ENV:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        id: step_one
        run: |
         echo "action_state=yellow" >> $custom_GITHUB_ENV
         
      - name: Use the value
        id: step_two
        run: |
            echo "{{env.action_state}}" #this will print yellow
